version: '3.4'

services: 
    app:
        build: .
        container_name: desafio-rdi-container
        command: "dotnet run"
        ports: 
            - 8081:80
            - 8082:443
        environment: 
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=https://+:443;http://+:80
            - ASPNETCORE_Kestrel__Certificates__Default__Password=CERT@13
            - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
        volumes:
            - ./certificate/https:/https/
    