version: '3.4'

services: 
    app:
        build: .
        container_name: desafio-rdi-container
        command: "dotnet run"
        ports: 
            - ${HTTP_PORT}:80
            - ${HTTPS_PORT}:443
        environment: 
            - ASPNETCORE_ENVIRONMENT=${ENVIRONMENT}
            - ASPNETCORE_URLS=https://+;http://+
            - ASPNETCORE_HTTP_PORT=${HTTP_PORT}
            - ASPNETCORE_HTTPS_PORT=${HTTPS_PORT}
            - ASPNETCORE_Kestrel__Certificates__Default__Password=${CERT_PASS}
            - ASPNETCORE_Kestrel__Certificates__Default__Path=${CERT_PATH}
        volumes:
            - ${CERT_FOLDER}:/https/
    